version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: debezium/postgres:14
    hostname: debezium_postgres_14
    container_name: debezium_postgres_14
    expose:
      - '5414'
    ports:
      - '5414:5414'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: -p 5414
    volumes:
      - ./data:/usr/share/postgresql/data
    networks:
      - debezium_postgres_14_network

volumes:
  data:
    name: debezium_postgres_14_data

networks:
  debezium_postgres_14_network:
    driver: bridge
    name: debezium_postgres_14_network